### ISSUE TITLE
requirements.txt where is

### ISSUE THREAD

**Issue by CARocha** [mtrgroup/django-mtr-sync#5]
Hi, when i install with pip and github, i have many error so many packages like that openpyxl,xlrd,xlwt, etc etc etc. is not install and  where is the file requirements.txt, for my is more easy install all dependencies.

Cheers

**Comment by yaroslavprogrammer** [comment]
Hi! Just updated docs, and setup.py for correct installation with all dependencies, just use:
`pip install git+https://github.com/mtrgroup/django-mtr-sync.git#egg=django-mtr-sync --process-dependency-links`
